from pygame.locals import *



SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 704
SCREEN_RECT = Rect(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT)

MAP_LIST_ROW = 22
MAP_LIST_COL = 40

MAP_CHIP_SIZE = 32
"""  マップチップの一辺のサイズ [px]  """

PLAYER_WIDTH = 32
PLAYER_HEIGHT = 32

FPS = 60

DIRECTION_LEFT  = 1
DIRECTION_RIGHT = 2
DIRECTION_UP    = 3
DIRECTION_DOWN  = 0
